"""Initial migration.

Revision ID: 7bec0b34050e
Revises: 
Create Date: 2023-12-15 05:02:40.138676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bec0b34050e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reg_prediction')
    op.drop_table('prediction')
    with op.batch_alter_table('classprediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classprediction', schema=None) as batch_op:
        batch_op.drop_column('prediction')

    op.create_table('prediction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_age', sa.FLOAT(), nullable=False),
    sa.Column('distance_to_MRT', sa.FLOAT(), nullable=False),
    sa.Column('num_convenience_stores', sa.INTEGER(), nullable=False),
    sa.Column('predicted_value', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reg_prediction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('house_age', sa.FLOAT(), nullable=False),
    sa.Column('distance_to_MRT', sa.FLOAT(), nullable=False),
    sa.Column('num_convenience_stores', sa.INTEGER(), nullable=False),
    sa.Column('predicted_value', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
